# Write your MySQL query statement below
SELECT ROUND(SUM(tiv_2016), 2) AS tiv_2016
FROM (SELECT *, COUNT(*) OVER (PARTITION BY tiv_2015) AS c1,
COUNT(*) OVER(PARTITION BY LAT, LON) AS c2 FROM INSURANCE)
AS TBL WHERE c1 >= 2 AND c2 = 1